/**
 * shadcn/ui コンポーネント一覧（静的スナップショット）
 *
 * このファイルは shadcn/ui の全コンポーネントを静的データとして管理する。
 * アプリケーション実行時に MCP サーバーへの通信は行わない。
 *
 * 更新方法:
 * Claude Code / Cursor に以下のプロンプトを送信する:
 * 「shadcn-registry.ts を最新化してください。
 *   MCP の list_components で最新のコンポーネント一覧を取得し、
 *   shadcn-registry.ts を更新してください。」
 *
 * 最終更新: 2026-03-08
 */
import type { ShadcnComponentEntry } from "./types";

export const shadcnComponents: ShadcnComponentEntry[] = [
  // ── Form ──────────────────────────────────────────────────────
  {
    name: "Button",
    slug: "button",
    description: "クリック可能なボタン。variant と size でバリエーション指定",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/button",
    installed: true,
  },
  {
    name: "Checkbox",
    slug: "checkbox",
    description: "チェックボックス。オン/オフの切り替えに使用",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/checkbox",
    installed: false,
  },
  {
    name: "Date Picker",
    slug: "date-picker",
    description: "日付選択コンポーネント。Popover + Calendar の組み合わせ",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/date-picker",
    installed: false,
  },
  {
    name: "Form",
    slug: "form",
    description: "React Hook Form ベースのフォームバリデーション",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/form",
    installed: false,
  },
  {
    name: "Input",
    slug: "input",
    description: "テキスト入力フィールド",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/input",
    installed: true,
  },
  {
    name: "Input OTP",
    slug: "input-otp",
    description: "ワンタイムパスワード入力コンポーネント",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/input-otp",
    installed: false,
  },
  {
    name: "Label",
    slug: "label",
    description: "フォームラベル。Input と組み合わせて使用",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/label",
    installed: true,
  },
  {
    name: "Radio Group",
    slug: "radio-group",
    description: "複数選択肢から1つを選択するラジオボタングループ",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/radio-group",
    installed: false,
  },
  {
    name: "Select",
    slug: "select",
    description: "ドロップダウン形式の選択コンポーネント",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/select",
    installed: false,
  },
  {
    name: "Slider",
    slug: "slider",
    description: "範囲値を選択するスライダー",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/slider",
    installed: false,
  },
  {
    name: "Switch",
    slug: "switch",
    description: "オン/オフを切り替えるトグルスイッチ",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/switch",
    installed: false,
  },
  {
    name: "Textarea",
    slug: "textarea",
    description: "複数行のテキスト入力フィールド",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/textarea",
    installed: false,
  },
  {
    name: "Toggle",
    slug: "toggle",
    description: "押下状態を持つトグルボタン",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/toggle",
    installed: false,
  },
  {
    name: "Toggle Group",
    slug: "toggle-group",
    description: "複数のトグルボタンをグループ化",
    category: "Form",
    docsUrl: "https://ui.shadcn.com/docs/components/toggle-group",
    installed: false,
  },

  // ── Data Display ──────────────────────────────────────────────
  {
    name: "Avatar",
    slug: "avatar",
    description: "ユーザーアバター画像。フォールバック表示対応",
    category: "Data Display",
    docsUrl: "https://ui.shadcn.com/docs/components/avatar",
    installed: true,
  },
  {
    name: "Badge",
    slug: "badge",
    description: "ステータスやカテゴリを示す小さなラベル",
    category: "Data Display",
    docsUrl: "https://ui.shadcn.com/docs/components/badge",
    installed: true,
  },
  {
    name: "Calendar",
    slug: "calendar",
    description: "カレンダー表示コンポーネント",
    category: "Data Display",
    docsUrl: "https://ui.shadcn.com/docs/components/calendar",
    installed: false,
  },
  {
    name: "Card",
    slug: "card",
    description: "カードコンテナ。Header, Title, Content 等と組み合わせ",
    category: "Data Display",
    docsUrl: "https://ui.shadcn.com/docs/components/card",
    installed: true,
  },
  {
    name: "Carousel",
    slug: "carousel",
    description: "スライド形式のカルーセルコンポーネント",
    category: "Data Display",
    docsUrl: "https://ui.shadcn.com/docs/components/carousel",
    installed: false,
  },
  {
    name: "Chart",
    slug: "chart",
    description: "Recharts ベースのチャートコンポーネント",
    category: "Data Display",
    docsUrl: "https://ui.shadcn.com/docs/components/chart",
    installed: false,
  },
  {
    name: "Table",
    slug: "table",
    description: "データテーブル。Header, Body, Row, Cell 等で構成",
    category: "Data Display",
    docsUrl: "https://ui.shadcn.com/docs/components/table",
    installed: true,
  },

  // ── Layout ────────────────────────────────────────────────────
  {
    name: "Accordion",
    slug: "accordion",
    description: "折りたたみ可能なコンテンツセクション",
    category: "Layout",
    docsUrl: "https://ui.shadcn.com/docs/components/accordion",
    installed: true,
  },
  {
    name: "Aspect Ratio",
    slug: "aspect-ratio",
    description: "コンテンツのアスペクト比を維持するコンテナ",
    category: "Layout",
    docsUrl: "https://ui.shadcn.com/docs/components/aspect-ratio",
    installed: false,
  },
  {
    name: "Collapsible",
    slug: "collapsible",
    description: "開閉可能なコンテナ",
    category: "Layout",
    docsUrl: "https://ui.shadcn.com/docs/components/collapsible",
    installed: true,
  },
  {
    name: "Resizable",
    slug: "resizable",
    description: "リサイズ可能なパネルレイアウト",
    category: "Layout",
    docsUrl: "https://ui.shadcn.com/docs/components/resizable",
    installed: false,
  },
  {
    name: "Scroll Area",
    slug: "scroll-area",
    description: "カスタムスクロールバー付きスクロール領域",
    category: "Layout",
    docsUrl: "https://ui.shadcn.com/docs/components/scroll-area",
    installed: true,
  },
  {
    name: "Separator",
    slug: "separator",
    description: "コンテンツ間の区切り線",
    category: "Layout",
    docsUrl: "https://ui.shadcn.com/docs/components/separator",
    installed: true,
  },
  {
    name: "Tabs",
    slug: "tabs",
    description: "タブ切り替えでコンテンツを表示",
    category: "Layout",
    docsUrl: "https://ui.shadcn.com/docs/components/tabs",
    installed: true,
  },

  // ── Navigation ────────────────────────────────────────────────
  {
    name: "Breadcrumb",
    slug: "breadcrumb",
    description: "パンくずリストナビゲーション",
    category: "Navigation",
    docsUrl: "https://ui.shadcn.com/docs/components/breadcrumb",
    installed: false,
  },
  {
    name: "Command",
    slug: "command",
    description: "コマンドパレット。検索・コマンド入力UI",
    category: "Navigation",
    docsUrl: "https://ui.shadcn.com/docs/components/command",
    installed: false,
  },
  {
    name: "Menubar",
    slug: "menubar",
    description: "デスクトップアプリ風のメニューバー",
    category: "Navigation",
    docsUrl: "https://ui.shadcn.com/docs/components/menubar",
    installed: false,
  },
  {
    name: "Navigation Menu",
    slug: "navigation-menu",
    description: "サイトナビゲーション用メニュー",
    category: "Navigation",
    docsUrl: "https://ui.shadcn.com/docs/components/navigation-menu",
    installed: false,
  },
  {
    name: "Pagination",
    slug: "pagination",
    description: "ページネーションコンポーネント",
    category: "Navigation",
    docsUrl: "https://ui.shadcn.com/docs/components/pagination",
    installed: false,
  },
  {
    name: "Sidebar",
    slug: "sidebar",
    description: "サイドバーナビゲーション",
    category: "Navigation",
    docsUrl: "https://ui.shadcn.com/docs/components/sidebar",
    installed: false,
  },

  // ── Feedback ──────────────────────────────────────────────────
  {
    name: "Alert",
    slug: "alert",
    description: "注意喚起メッセージの表示",
    category: "Feedback",
    docsUrl: "https://ui.shadcn.com/docs/components/alert",
    installed: false,
  },
  {
    name: "Alert Dialog",
    slug: "alert-dialog",
    description: "確認ダイアログ。破壊的操作の確認に使用",
    category: "Feedback",
    docsUrl: "https://ui.shadcn.com/docs/components/alert-dialog",
    installed: false,
  },
  {
    name: "Progress",
    slug: "progress",
    description: "進捗表示バー",
    category: "Feedback",
    docsUrl: "https://ui.shadcn.com/docs/components/progress",
    installed: false,
  },
  {
    name: "Skeleton",
    slug: "skeleton",
    description: "ローディング中のプレースホルダー表示",
    category: "Feedback",
    docsUrl: "https://ui.shadcn.com/docs/components/skeleton",
    installed: false,
  },
  {
    name: "Sonner",
    slug: "sonner",
    description: "トースト通知（Sonner ベース）",
    category: "Feedback",
    docsUrl: "https://ui.shadcn.com/docs/components/sonner",
    installed: false,
  },
  {
    name: "Toast",
    slug: "toast",
    description: "トースト通知コンポーネント",
    category: "Feedback",
    docsUrl: "https://ui.shadcn.com/docs/components/toast",
    installed: false,
  },

  // ── Overlay ───────────────────────────────────────────────────
  {
    name: "Context Menu",
    slug: "context-menu",
    description: "右クリックで表示するコンテキストメニュー",
    category: "Overlay",
    docsUrl: "https://ui.shadcn.com/docs/components/context-menu",
    installed: false,
  },
  {
    name: "Dialog",
    slug: "dialog",
    description: "モーダルダイアログ",
    category: "Overlay",
    docsUrl: "https://ui.shadcn.com/docs/components/dialog",
    installed: false,
  },
  {
    name: "Drawer",
    slug: "drawer",
    description: "画面端からスライドインするパネル",
    category: "Overlay",
    docsUrl: "https://ui.shadcn.com/docs/components/drawer",
    installed: false,
  },
  {
    name: "Dropdown Menu",
    slug: "dropdown-menu",
    description: "ドロップダウンメニュー。アクション一覧の表示に使用",
    category: "Overlay",
    docsUrl: "https://ui.shadcn.com/docs/components/dropdown-menu",
    installed: true,
  },
  {
    name: "Hover Card",
    slug: "hover-card",
    description: "ホバー時にポップアップ表示するカード",
    category: "Overlay",
    docsUrl: "https://ui.shadcn.com/docs/components/hover-card",
    installed: false,
  },
  {
    name: "Popover",
    slug: "popover",
    description: "クリックで表示するポップオーバー",
    category: "Overlay",
    docsUrl: "https://ui.shadcn.com/docs/components/popover",
    installed: false,
  },
  {
    name: "Sheet",
    slug: "sheet",
    description: "画面端からスライドインするパネル（Dialog 拡張）",
    category: "Overlay",
    docsUrl: "https://ui.shadcn.com/docs/components/sheet",
    installed: false,
  },
  {
    name: "Tooltip",
    slug: "tooltip",
    description: "ホバー時に表示する補足情報ツールチップ",
    category: "Overlay",
    docsUrl: "https://ui.shadcn.com/docs/components/tooltip",
    installed: false,
  },
];

/** カテゴリの表示順序 */
export const categoryOrder: ShadcnComponentEntry["category"][] = [
  "Form",
  "Data Display",
  "Layout",
  "Navigation",
  "Feedback",
  "Overlay",
];
